spring:
  application:
    name: tlias-web-management
  servlet:
    multipart:
      max-file-size: 10MB # 单个文件最大限制
      max-request-size: 100MB # 总请求大小最大限制
    #配置数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    #url: jdbc:mysql://192.168.100.128:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

#mybatis的相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启了驼峰命名映射的开关
    map-underscore-to-camel-case: true

#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

server:
  port: 8080
  #配置事务管理日志级别
  logging:
    level:
      org.springframework.jdbc.support.JdbcTransactionManager: debug

#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: xuan-ai-java
    region: cn-beijing
